receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
  otlp/traces:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4417"
  filelog:
    include: [ /var/log/sre/minhaApp.log ]

exporters:
  prometheusremotewrite:
    endpoint: "http://mimir:9009/api/v1/push"
  otlphttp/loki:
    endpoint: http://loki:3100/loki/api/v1/push
  otlp/traces:
    endpoint: tempo:4517
    tls:
      insecure: true
  debug:

processors:
  batch:
  resource:
    attributes:
    - key: service_name
      value: "metal-app"
      action: upsert
    - key: deployment_environment
      value: "dev"
      action: upsert
    - action: insert
      key: loki.resource.labels
      value: service_name, deployment_environment
  tail_sampling:
    decision_wait: 10s
    policies:
      [
        {
          name: errors-policy,
          type: status_code,
          status_code: { status_codes: [ERROR] }
        },
        {
          name: randomized-policy,
          type: probabilistic,
          probabilistic: { sampling_percentage: 100 },
        },
      ]

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite,debug]
      processors: [resource,batch]
    logs:
      receivers: [filelog]
      processors: [resource]
      exporters: [otlphttp/loki]
    traces:
      receivers: [otlp/traces]
      # processors: [resource,tail_sampling]
      processors: [resource]
      exporters: [otlp/traces]
  telemetry:
    logs:
      level: debug
