multitenancy_enabled: false

blocks_storage:
  tsdb:
    dir: /tmp/mimir/tsdb

compactor:
  data_dir: /tmp/mimir/compactor

ruler_storage:
  backend: local
  local:
    directory: /data/mimir/rules

server:
  http_listen_port: 9009

limits:
  ingestion_rate: 10000
  ingestion_burst_size: 20000

ingester:
  ring:
    kvstore:
      store: inmemory  # Use in-memory kvstore (no distributed ring)
    replication_factor: 1 

distributor:
  ring:
    kvstore:
      store: inmemory  # In-memory kvstore for distributor (no multiple instances)
