global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "extraindo-metricas-do-grafana"
    static_configs:
      - targets: ["grafana:3000"]
  - job_name: "extraindo-metricas-do-otel-collector"
    static_configs:
      - targets: ["collector:9464"]

remote_write:
  - url: "http://mimir:9009/api/v1/push"
    send_exemplars: true
